name: Build

on:
  push:
    branches:
      - main


jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    services:
      sonarqube:
        image: sonarqube:latest
        ports:
          - 9000:9000
        options: --health-cmd='curl -f http://localhost:9000/api/system/health' --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Wait for SonarQube to be up and running
        run: |
          until $(curl -o /dev/null -s -f http://localhost:9000/api/system/status); do
            echo "Waiting for SonarQube to start..."
            sleep 5
          done

      - name: SonarQube Scan
        env:
          SONAR_HOST_URL: "http://localhost:9000"
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        uses: sonarsource/sonarqube-scan-action@v3
