name: UnitTests

on: 
  workflow_dispatch:
  workflow_run:
    workflows: ['PylintAndPrecommit']
    types: [completed] 


jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        python-version: ["3.10.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Executing pytest, triggering all valid tests in project
      run: |
        pytest